name: masklab
favicon: null
layout_spectrum: 0.2505
typography_spectrum: 0.0781371807679534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7209114660508931
  lightness: 0.8753391786012799
  saturation: 0.5008760720957071
  rhythmicContrast: 0.9224386403802782
purpose: []
